### ISSUE TITLE
Teledrive crashes with SIGSEGV on startup

### ISSUE THREAD

**Issue by dslotter** [KhushrajRathod/TeleDrive#119]
I tried googling this and could not find a suitable fix or workaround, so filing this defect report.

dave@Pluto:~/projects/TeleDrive$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 20.60s.
dave@Pluto:~/projects/TeleDrive$ yarn start
yarn run v1.22.17
$ electron .
/home/dave/projects/TeleDrive/node_modules/electron/dist/electron exited with signal SIGSEGV
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I found how to run yarn with verbose output:

dave@Pluto:~/projects/TeleDrive$ yarn --verbose start
yarn run v1.22.17
verbose 0.329063467 Checking for configuration file "/home/dave/projects/TeleDrive/.npmrc".
verbose 0.32984086 Checking for configuration file "/home/dave/.npmrc".
verbose 0.330133725 Checking for configuration file "/usr/etc/npmrc".
verbose 0.330820745 Checking for configuration file "/home/dave/projects/TeleDrive/.npmrc".
verbose 0.33156761 Checking for configuration file "/home/dave/projects/.npmrc".
verbose 0.332511673 Checking for configuration file "/home/dave/.npmrc".
verbose 0.333180968 Checking for configuration file "/home/.npmrc".
verbose 0.335626429 Checking for configuration file "/home/dave/projects/TeleDrive/.yarnrc".
verbose 0.33629815 Checking for configuration file "/home/dave/.yarnrc".
verbose 0.336704096 Found configuration file "/home/dave/.yarnrc".
verbose 0.337166518 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.337603424 Checking for configuration file "/home/dave/projects/TeleDrive/.yarnrc".
verbose 0.337867444 Checking for configuration file "/home/dave/projects/.yarnrc".
verbose 0.338077686 Checking for configuration file "/home/dave/.yarnrc".
verbose 0.338431397 Found configuration file "/home/dave/.yarnrc".
verbose 0.338835689 Checking for configuration file "/home/.yarnrc".
verbose 0.34589468 current time: 2022-01-12T14:17:45.795Z
$ electron .
/home/dave/projects/TeleDrive/node_modules/electron/dist/electron exited with signal SIGSEGV
verbose 1.239582432 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:790:113)
    at /usr/share/yarn/lib/cli.js:34672:30
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dslotter** [comment]
This issue has been open for six weeks now with no response. Hoping that this comment will attract attention.
